name: Sync Azure DevOps to GitHub

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight, adjust as needed

jobs:
  sync_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Base64-encoded Auth Header
        env:
          MY_PAT: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        run: |
          # Create the Base64 encoded token
          echo "::set-output name=encoded_pat::$(echo -n \":$MY_PAT\" | base64)"

      - name: Clone Azure DevOps Repository
        env:
          AZURE_DEVOPS_URL: ${{ secrets.AZURE_DEVOPS_REPO_URL }}
          B64_PAT: ${{ steps.set-up-auth.outputs.encoded_pat }}
        run: |
          # Clone directly from Azure DevOps using the Base64 token
          git -c http.extraHeader="Authorization: Basic ${B64_PAT}" clone $AZURE_DEVOPS_URL .

      - name: Push to GitHub Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Push the cloned content to the GitHub repository
          git push --mirror https://github.com/${{ github.repository }}.git
