name: Sync Azure DevOps to GitHub

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight, adjust as needed

jobs:
  sync_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Pull from Azure DevOps
        env:
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        run: |
          # Check if the Azure remote already exists, add it if not
          if ! git remote get-url azure; then
            git remote add azure ${{ secrets.AZURE_DEVOPS_REPO_URL }}
          fi

          # Configure authentication
          git config --global http.extraHeader "Authorization: Basic $(echo -n :$AZURE_DEVOPS_TOKEN | base64)"

          # Fetch and pull from Azure DevOps
          git fetch azure
          git checkout -B main azure/main # Replace 'main' with your Azure DevOps branch name if different
          git pull azure main # This pulls in the latest changes

      - name: Add GitHub Remote
        run: |
          # Remove the existing GitHub remote if it exists
          git remote remove github || echo "No remote named 'github' found"
          
          # Add the GitHub remote
          git remote add github https://github.com/${{ github.repository }}.git

      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push github main --force # Overwrites main on GitHub
