name: Sync Workflow

on:
  workflow_dispatch:
    inputs:
      subscriptionId:
        description: 'The subscription ID for the event'
        required: true
        default: ''
      notificationId:
        description: 'The notification ID for the event'
        required: true
        default: ''
      eventType:
        description: 'The type of event triggering this workflow'
        required: true
        default: ''
      # Add additional inputs as needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync Code
        run: echo "Syncing code..."

      - name: Generate Changelog
        uses: rhysd/changelog-from-release/action@v2
        with:
          file: CHANGELOG.md
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Process Incoming Data
        run: |
          echo "Subscription ID: ${{ github.event.inputs.subscriptionId }}"
          echo "Notification ID: ${{ github.event.inputs.notificationId }}"
          echo "Event Type: ${{ github.event.inputs.eventType }}"
