name: Sync Azure DevOps to GitHub

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight, adjust as needed

jobs:
  sync_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout an empty repo
        uses: actions/checkout@v2
        with:
          # Use the current repository to create an empty working directory
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Pull from Azure DevOps
        env:
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        run: |
          git init
          git remote add origin ${{ secrets.AZURE_DEVOPS_REPO_URL }}
          git config --global http.extraHeader "Authorization: Basic $(echo -n :$AZURE_DEVOPS_TOKEN | base64)"
          git pull origin main # Replace 'main' with the branch name in Azure DevOps if different

      - name: Add GitHub Remote
        run: |
          # Remove the existing github remote if it exists
          git remote remove github || echo "No remote named 'github' found"
          git remote add github https://github.com/${{ github.repository }}.git

      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push github main --force # Overwrites main on GitHub
