name: Sync Azure DevOps to GitHub

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight, adjust as needed

jobs:
  sync_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Add Azure DevOps Remote and Pull
        env:
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          AZURE_DEVOPS_REPO_URL: ${{ secrets.AZURE_DEVOPS_REPO_URL }}
        run: |
          # Add Azure DevOps remote if it doesn't exist
          git remote | grep azure || git remote add azure "$AZURE_DEVOPS_REPO_URL"

          # Configure the authentication header for Azure DevOps using base64-encoded PAT
          B64_PAT=$(echo -n ":$AZURE_DEVOPS_TOKEN" | base64)
          git -c http.extraHeader="Authorization: Basic ${B64_PAT}" fetch azure

          # Check out and update the main branch from Azure DevOps
          git checkout -B main azure/main
          git pull azure main

      - name: Add GitHub Remote
        run: |
          # Remove existing GitHub remote if it exists
          git remote remove github || echo "No remote named 'github' found"
          
          # Add GitHub as a remote
          git remote add github https://github.com/${{ github.repository }}.git

      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Push to GitHub main branch, using force if necessary
          git push github main --force
