name: Sync Azure DevOps to GitHub

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight, adjust as needed

jobs:
  sync_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Base64-encoded Auth Header
        id: set-up-auth
        env:
          MY_PAT: ${{ secrets.AZURE_DEVOPS_TOKEN }}  # Your PAT secret
        run: |
          # Encode PAT in Base64
          B64_PAT=$(echo -n ":$MY_PAT" | base64)
          echo "Encoded PAT: $B64_PAT"  # Log the encoded PAT (caution with sensitive data)
          echo "encoded_pat=$B64_PAT" >> $GITHUB_ENV  # Set encoded PAT as an environment variable

      - name: Clone Azure DevOps Repository
        env:
          AZURE_DEVOPS_URL: 'https://dev.azure.com/taskdevai/Client%20Azure/_git/Client%20Azure/'  # Hardcoded repo URL
          B64_PAT: ${{ env.encoded_pat }}  # Use the encoded PAT
        run: |
          echo "Cloning repository from: ${AZURE_DEVOPS_URL}"  # Log the Azure DevOps URL
          # Clone directly into a directory named 'azure_repo'
          git -c http.extraHeader="Authorization: Basic ${B64_PAT}" clone "${AZURE_DEVOPS_URL}" azure_repo || { echo "Clone failed"; exit 1; }
          
          # Change into the cloned directory
          cd azure_repo || { echo "Failed to change directory"; exit 1; }

      - name: Push to GitHub Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Adding GitHub remote..."  # Log before adding the remote
          # Change into the azure_repo directory to push changes
          cd azure_repo || { echo "Failed to change directory to azure_repo"; exit 1; }
          git remote add github https://github.com/${{ github.repository }}.git
          echo "Pushing changes to GitHub..."  # Log before pushing
          git push github main --force || { echo "Push failed"; exit 1; }
